(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'1229757c-4f1a-4459-92bb-c1fe62def929-bootstrap-container',
          componentName:'ContactForm3',
          props:props,
          context:context,
          contextKey:'context-1229757c-4f1a-4459-92bb-c1fe62def929-bootstrap-container',
          radpack:false
        });
      })({"formTitle":"","formFields":[{"type":"SINGLE_LINE","label":"Name","required":false,"keyName":"name"},{"type":"EMAIL","label":"Email","validation":"email","required":true,"replyTo":true,"keyName":"email"},{"label":"Severity","type":"SINGLE_LINE","required":true},{"label":"Service Type","type":"SINGLE_LINE","required":true},{"type":"MULTI_LINE","label":"Message","required":false,"keyName":"message"},{"type":"ATTACHMENT","label":"Attachments","required":false},{"type":"SUBMIT","label":"Send","required":false}],"blankInfo":false,"formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","recaptchaEnabled":true,"recaptchaType":"V3","domainName":"machosting.club","formSuccessMessage":"Thank you for your inquiry! We will get back to you within 48 hours.","formEnabled":true,"websiteId":"0aa640bc-3bff-41d5-83fb-228636f1ac29","pageId":"8b9f3f9c-0cc8-4684-8eb6-644bf5bc4b4e","accountId":"595c2d2e-ff08-11ea-81eb-3417ebe725c2","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","phoneValidationErrorMessage":"Please enter a valid phone number.","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","unsupportedFileType":"Unsupported file type","maxFileCountLimit":"Only {0} files are allowed","closed":"Closed","attachments":"Attachments","termsOfSerivce":"Terms of Service","attachFiles":"Attach Files","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","couldNotAttach":"Could not attach the following file(s)","totalFileSizeLimit":"Total files would exceed {0} limit","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms","fileSizeLimit":"File exceeds {0} limit","emailMaxCountValidationErrorMessage":"Your email address is too long"},"emailOptInEnabled":false,"emailOptInHidden":false,"emailOptInMessage":"Sign up for our email list for updates, promotions, and more.","emailConfirmationMessage":"We've sent you a confirmation email, please click the link to verify your address.","widgetId":"1229757c-4f1a-4459-92bb-c1fe62def929","section":"default","category":"neutral","locale":"en-PH","renderMode":"PUBLISH"},{"widgetId":"1229757c-4f1a-4459-92bb-c1fe62def929","widgetType":"CONTACT","widgetPreset":"contact8","section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default","websiteThemeOverrides":{},"widgetThemeOverrides":{}});